In [1]:
import numpy as np

Creating a Matrix using Numpy

In [3]:
matrix_1= np.array([[1,7],[2,0]])
print(matrix_1)

[[1 7]
 [2 0]]


In [7]:
matrix_1.shape

(2, 2)

In [8]:
matrix_2 = np.array([[1,2,0],[7,0,0],[5,6,2]])
print(matrix_2)

[[1 2 0]
 [7 0 0]
 [5 6 2]]


In [9]:
matrix_2.shape

(3, 3)

Creating Matrix with Random values

In [11]:
random_matrix= np.random.rand(7,9)
print(random_matrix)

[[0.98603296 0.64830551 0.81485646 0.06035789 0.96422038 0.24521934
  0.96009991 0.48648169 0.95026464]
 [0.45429331 0.68428381 0.36837786 0.75602409 0.79037018 0.63491169
  0.02359421 0.39881447 0.40252408]
 [0.20854303 0.49306346 0.33697106 0.41990479 0.79817374 0.03394452
  0.61723856 0.90725771 0.00203001]
 [0.50717509 0.75829549 0.24082813 0.31466893 0.70036734 0.38897145
  0.95213807 0.6861618  0.45194768]
 [0.75417123 0.6838568  0.86407888 0.76831082 0.12305779 0.93512858
  0.13811546 0.26657286 0.58463059]
 [0.01932728 0.82795132 0.25123943 0.00173851 0.50361123 0.50483361
  0.70762679 0.7707723  0.41604778]
 [0.60506222 0.43724326 0.19222212 0.03088993 0.62517878 0.08349526
  0.51154705 0.26259177 0.65679268]]


In [14]:
random_integers_matrix = np.random.randint(100, size=(8,9))
print(random_integers_matrix)

[[89 25 75 97 49 68 33 60  0]
 [25 22 13 65 60 70 14 33 38]
 [53 35 71 93 89 53 95 13 50]
 [47  3 37 14 23  9 56 56  2]
 [ 0 68 65 75  1 57 78 48 43]
 [47 30 40 90 23 16 20  9 91]
 [37 75 75 43 85 97 31 92 28]
 [45 48 53 71 25 40 40 95 13]]


Matrix with all value one

In [16]:
matrix_3=np.ones((3,4),dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Matrix with all value zero

In [19]:
matrix_4 = np.zeros((5,5),dtype=int)
print(matrix_4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Identity Matrix

In [26]:
identity_matrix = np.eye(7,9,dtype=int)
print(identity_matrix)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]]


Transpose Matrix

In [23]:
a = np.random.randint(100, size=(5,6))
print(a)

[[37 60 75 66 44 33]
 [98 71 27 67 98  8]
 [78 54 14 93 53 11]
 [21 75 83 19 98 92]
 [38 53 61 28 54 32]]


In [25]:
Transpose_a= np.transpose(a)
print(Transpose_a)

[[37 98 78 21 38]
 [60 71 54 75 53]
 [75 27 14 83 61]
 [66 67 93 19 28]
 [44 98 53 98 54]
 [33  8 11 92 32]]
