In [1]:
import numpy as np

Add Two Matrix

In [3]:
a = np.array([[1,7],[1,2]])
b = np.array([[2,0],[0,9]])
c = a+b
print(c)

[[ 3  7]
 [ 1 11]]


Subtract Two Matrix

In [8]:
a = np.random.randint(100,size=(3,3))
b= np.random.randint(100, size=(3,3))
print("First Matrix \n",a)
print()
print("Second Matrix \n" ,b)
print()
c= a+b
print("Addition of Two Matrix \n ",c)

First Matrix 
 [[91 77 57]
 [70 73 13]
 [99 27 96]]

Second Matrix 
 [[65 76 56]
 [20  4 79]
 [90 54 62]]

Addition of Two Matrix 
  [[156 153 113]
 [ 90  77  92]
 [189  81 158]]


In [10]:
sum=np.add(a,b)
print(sum)


[[156 153 113]
 [ 90  77  92]
 [189  81 158]]


In [13]:
a = np.random.randint(100,size=(3,3))
b= np.random.randint(100, size=(3,3))
print("First Matrix \n",a)
print()
print("Second Matrix \n" ,b)
print()
c = np.subtract(a,b)
print("Subtraction of Two Matrix \n ",c)

First Matrix 
 [[66 97 93]
 [60 42  9]
 [78 11 63]]

Second Matrix 
 [[26 38 59]
 [39 69 86]
 [77  7 84]]

Subtraction of Two Matrix 
  [[ 40  59  34]
 [ 21 -27 -77]
 [  1   4 -21]]


Multiplying a Matrix by a Scalar

In [17]:
x = 5
y = np.random.randint(100,size=(3,3))
print("Your Matrix is :\n",y)
print("Your Scalar is :\n",x)
print("Multiplication of Matrix and Scalar is :")
print(x*y)

Your Matrix is :
 [[96 53 79]
 [37 50 35]
 [88 77 81]]
Your Scalar is :
 5
Multiplication of Matrix and Scalar is :
[[480 265 395]
 [185 250 175]
 [440 385 405]]


**Multiplying Two Matrix**

Rule = No of column in first matrix is equal to the no rows in the second Matrix and the resultant Matrix will have same no of column in first matrix and the same no of rows at the second matrix  

In [18]:
a = np.random.randint(100,size=(3,3))
b= np.random.randint(100, size=(3,3))
print("First Matrix \n",a)
print()
print("Second Matrix \n" ,b)
print()
c = np.dot(a,b)
print("Multiplication of Two Matrix \n ",c)

First Matrix 
 [[15 11 38]
 [92 15 22]
 [49 23 67]]

Second Matrix 
 [[53 59 64]
 [86 80 81]
 [68 28 33]]

Multiplication of Two Matrix 
  [[4325 2829 3105]
 [7662 7244 7829]
 [9131 6607 7210]]


In [19]:
a.shape
b.shape
c.shape

(3, 3)

Multiply code is used to multiply element wise multiplication

In [20]:
d = np.multiply(a,b)
print(d)

[[ 795  649 2432]
 [7912 1200 1782]
 [3332  644 2211]]
